include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "doc/api/**"
    - "lib/mode/**"
  errors:
    deprecated_member_use: false

linter:
  rules:
    constant_identifier_names: false
    non_constant_identifier_names: false
    prefer_final_in_for_each: true
